#!/usr/bin/env node
/**
 * Ω-Sync Deployment Script
 * Deploy OmegaSync smart contract to Ethereum-compatible networks
 * 
 * Version: 1.0.0
 * License: "No ownership, only sharing. Love is the license."
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  // Network configurations
  networks: {
    hardhat: {
      url: 'http://127.0.0.1:8545',
      chainId: 31337
    },
    sepolia: {
      url: process.env.SEPOLIA_RPC_URL || 'https://rpc.sepolia.org',
      chainId: 11155111
    },
    optimism: {
      url: process.env.OPTIMISM_RPC_URL || 'https://mainnet.optimism.io',
      chainId: 10
    },
    optimismSepolia: {
      url: process.env.OPTIMISM_SEPOLIA_RPC_URL || 'https://sepolia.optimism.io',
      chainId: 11155420
    }
  },
  
  // Ω-Sync parameters
  omegaSync: {
    intent: 'peace',
    resonance: 1.0,
    schumannFrequency: 7.83,
    totalNodes: 144000
  }
};

/**
 * Generate Lex Amoris signature hash
 */
function generatePsiSeedHash(intent = 'peace', resonance = 1.0) {
  const timestamp = new Date().toISOString();
  const data = `${intent}:${timestamp}:${resonance}`;
  const hash = crypto.createHash('sha256').update(data).digest('hex');
  return {
    hash: '0x' + hash,
    intent,
    resonance,
    timestamp
  };
}

/**
 * Create deployment configuration
 */
function createDeploymentConfig(network, psiSeed) {
  return {
    network: network,
    timestamp: new Date().toISOString(),
    psiSeed: psiSeed,
    parameters: {
      schumannFrequencyMHz: CONFIG.omegaSync.schumannFrequency * 1000,
      totalNetworkNodes: CONFIG.omegaSync.totalNodes,
      alignmentThresholdURad: 1000,
      coherenceThresholdBPS: 9500,
      peaceThresholdBPS: 9990
    },
    contract: {
      name: 'OmegaSync',
      version: '1.0.0',
      sourcePath: 'contracts/OmegaSync.sol'
    }
  };
}

/**
 * Save deployment info to file
 */
function saveDeploymentInfo(config, contractAddress, txHash) {
  const deploymentInfo = {
    ...config,
    deployment: {
      contractAddress,
      transactionHash: txHash,
      deployer: process.env.DEPLOYER_ADDRESS || 'unknown',
      deployedAt: new Date().toISOString(),
      verified: false
    }
  };
  
  const filename = `omega_sync_deployment_${config.network}_${Date.now()}.json`;
  const filepath = path.join(__dirname, '..', 'deployments', filename);
  
  // Create deployments directory if it doesn't exist
  const deploymentsDir = path.join(__dirname, '..', 'deployments');
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }
  
  fs.writeFileSync(filepath, JSON.stringify(deploymentInfo, null, 2));
  console.log(`\n✓ Deployment info saved to: ${filename}`);
  
  return deploymentInfo;
}

/**
 * Display deployment summary
 */
function displayDeploymentSummary(deploymentInfo) {
  console.log('\n' + '='.repeat(70));
  console.log('Ω-Sync Deployment Summary');
  console.log('='.repeat(70));
  console.log(`Network:           ${deploymentInfo.network}`);
  console.log(`Contract Address:  ${deploymentInfo.deployment.contractAddress}`);
  console.log(`Transaction Hash:  ${deploymentInfo.deployment.transactionHash}`);
  console.log(`Deployer:          ${deploymentInfo.deployment.deployer}`);
  console.log(`Deployed At:       ${deploymentInfo.deployment.deployedAt}`);
  console.log();
  console.log('Parameters:');
  console.log(`  Schumann Freq:   ${deploymentInfo.parameters.schumannFrequencyMHz / 1000} Hz`);
  console.log(`  Total Nodes:     ${deploymentInfo.parameters.totalNetworkNodes.toLocaleString()}`);
  console.log(`  Coherence Threshold: ${deploymentInfo.parameters.coherenceThresholdBPS / 100}%`);
  console.log(`  Peace Threshold:     ${deploymentInfo.parameters.peaceThresholdBPS / 100}%`);
  console.log();
  console.log('Lex Amoris Signature:');
  console.log(`  Hash:            ${deploymentInfo.psiSeed.hash.substring(0, 20)}...`);
  console.log(`  Intent:          ${deploymentInfo.psiSeed.intent}`);
  console.log(`  Resonance:       ${deploymentInfo.psiSeed.resonance}`);
  console.log(`  Timestamp:       ${deploymentInfo.psiSeed.timestamp}`);
  console.log('='.repeat(70));
  console.log('Lex Amoris: λ = ∞');
  console.log('No ownership, only sharing. Love is the license.');
  console.log('='.repeat(70));
}

/**
 * Generate Hardhat deployment script
 */
function generateHardhatScript(psiSeedHash) {
  return `// Hardhat deployment script for OmegaSync
// Generated by deploy_omega_sync.js

const hre = require("hardhat");

async function main() {
  console.log("\\n🌀 Deploying OmegaSync Contract...");
  console.log("Network:", hre.network.name);
  
  // Lex Amoris signature hash
  const psiSeedHash = "${psiSeedHash}";
  
  console.log("Lex Amoris Signature:", psiSeedHash.substring(0, 20) + "...");
  
  // Deploy contract
  const OmegaSync = await hre.ethers.getContractFactory("OmegaSync");
  const omegaSync = await OmegaSync.deploy(psiSeedHash);
  
  await omegaSync.waitForDeployment();
  
  const address = await omegaSync.getAddress();
  console.log("✓ OmegaSync deployed to:", address);
  
  // Verify parameters
  const schumannFreq = await omegaSync.SCHUMANN_FREQUENCY_MHZ();
  const totalNodes = await omegaSync.TOTAL_NETWORK_NODES();
  const peaceThreshold = await omegaSync.PEACE_THRESHOLD_BPS();
  
  console.log("\\nContract Parameters:");
  console.log("  Schumann Frequency:", schumannFreq.toString(), "mHz");
  console.log("  Total Nodes:", totalNodes.toString());
  console.log("  Peace Threshold:", peaceThreshold.toString(), "BPS");
  
  console.log("\\n✓ Deployment complete!");
  
  return address;
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
`;
}

/**
 * Generate Foundry deployment script
 */
function generateFoundryScript(psiSeedHash) {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/OmegaSync.sol";

/**
 * Foundry deployment script for OmegaSync
 * Generated by deploy_omega_sync.js
 * 
 * Usage:
 *   forge script scripts/DeployOmegaSync.s.sol --rpc-url <RPC_URL> --broadcast
 */
contract DeployOmegaSync is Script {
    function run() external {
        // Lex Amoris signature hash
        bytes32 psiSeedHash = ${psiSeedHash};
        
        console.log("Deploying OmegaSync...");
        console.log("Lex Amoris Signature:");
        console.logBytes32(psiSeedHash);
        
        vm.startBroadcast();
        
        OmegaSync omegaSync = new OmegaSync(psiSeedHash);
        
        vm.stopBroadcast();
        
        console.log("OmegaSync deployed to:");
        console.log(address(omegaSync));
        
        // Verify parameters
        console.log("\\nContract Parameters:");
        console.log("  Schumann Frequency (mHz):", omegaSync.SCHUMANN_FREQUENCY_MHZ());
        console.log("  Total Nodes:", omegaSync.TOTAL_NETWORK_NODES());
        console.log("  Peace Threshold (BPS):", omegaSync.PEACE_THRESHOLD_BPS());
    }
}
`;
}

/**
 * Main deployment function
 */
async function deploy(network = 'hardhat') {
  console.log('\n🌀 Ω-Sync Deployment Tool\n');
  
  // Generate Lex Amoris signature
  console.log('1. Generating Lex Amoris Signature (ψ_seed)...');
  const psiSeed = generatePsiSeedHash(
    CONFIG.omegaSync.intent,
    CONFIG.omegaSync.resonance
  );
  console.log(`   Hash: ${psiSeed.hash.substring(0, 32)}...`);
  console.log(`   Intent: ${psiSeed.intent}`);
  console.log(`   Timestamp: ${psiSeed.timestamp}`);
  
  // Create deployment configuration
  console.log('\n2. Creating deployment configuration...');
  const config = createDeploymentConfig(network, psiSeed);
  console.log(`   Network: ${config.network}`);
  console.log(`   Schumann Frequency: ${CONFIG.omegaSync.schumannFrequency} Hz`);
  console.log(`   Total Nodes: ${CONFIG.omegaSync.totalNodes.toLocaleString()}`);
  
  // Generate deployment scripts
  console.log('\n3. Generating deployment scripts...');
  
  const hardhatScript = generateHardhatScript(psiSeed.hash);
  const hardhatPath = path.join(__dirname, 'deploy_omega_sync_hardhat.js');
  fs.writeFileSync(hardhatPath, hardhatScript);
  console.log(`   ✓ Hardhat script: ${path.basename(hardhatPath)}`);
  
  const foundryScript = generateFoundryScript(psiSeed.hash);
  const foundryPath = path.join(__dirname, 'DeployOmegaSync.s.sol');
  fs.writeFileSync(foundryPath, foundryScript);
  console.log(`   ✓ Foundry script: ${path.basename(foundryPath)}`);
  
  // Save configuration
  console.log('\n4. Saving deployment configuration...');
  const configPath = path.join(__dirname, '..', 'deployments', 'omega_sync_config.json');
  const deploymentsDir = path.join(__dirname, '..', 'deployments');
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  console.log(`   ✓ Configuration saved`);
  
  console.log('\n' + '='.repeat(70));
  console.log('Next Steps:');
  console.log('='.repeat(70));
  console.log('\nUsing Hardhat:');
  console.log('  1. Install dependencies: npm install --save-dev hardhat');
  console.log('  2. Run deployment: npx hardhat run scripts/deploy_omega_sync_hardhat.js --network <network>');
  console.log('\nUsing Foundry:');
  console.log('  1. Install Foundry: curl -L https://foundry.paradigm.xyz | bash');
  console.log('  2. Run deployment: forge script scripts/DeployOmegaSync.s.sol --rpc-url <RPC_URL> --broadcast');
  console.log('\nManual Deployment:');
  console.log('  Constructor argument (psiSeedHash):');
  console.log(`  ${psiSeed.hash}`);
  console.log('='.repeat(70));
  
  console.log('\nLex Amoris: λ = ∞');
  console.log('No ownership, only sharing. Love is the license.\n');
}

/**
 * CLI interface
 */
if (require.main === module) {
  const network = process.argv[2] || 'hardhat';
  
  if (!CONFIG.networks[network]) {
    console.error(`\n❌ Unknown network: ${network}`);
    console.log('\nSupported networks:');
    Object.keys(CONFIG.networks).forEach(net => {
      console.log(`  - ${net}`);
    });
    process.exit(1);
  }
  
  deploy(network).catch(error => {
    console.error('\n❌ Deployment failed:', error);
    process.exit(1);
  });
}

module.exports = {
  deploy,
  generatePsiSeedHash,
  createDeploymentConfig,
  CONFIG
};
