// Hardhat deployment script for OmegaSync
// Generated by deploy_omega_sync.js

const hre = require("hardhat");

async function main() {
  console.log("\n🌀 Deploying OmegaSync Contract...");
  console.log("Network:", hre.network.name);
  
  // Lex Amoris signature hash
  const psiSeedHash = "0x87312bcfc82f77e819e9e8861f5076387426188830a9db74b6dd87f6a9d491a2";
  
  console.log("Lex Amoris Signature:", psiSeedHash.substring(0, 20) + "...");
  
  // Deploy contract
  const OmegaSync = await hre.ethers.getContractFactory("OmegaSync");
  const omegaSync = await OmegaSync.deploy(psiSeedHash);
  
  await omegaSync.waitForDeployment();
  
  const address = await omegaSync.getAddress();
  console.log("✓ OmegaSync deployed to:", address);
  
  // Verify parameters
  const schumannFreq = await omegaSync.SCHUMANN_FREQUENCY_MHZ();
  const totalNodes = await omegaSync.TOTAL_NETWORK_NODES();
  const peaceThreshold = await omegaSync.PEACE_THRESHOLD_BPS();
  
  console.log("\nContract Parameters:");
  console.log("  Schumann Frequency:", schumannFreq.toString(), "mHz");
  console.log("  Total Nodes:", totalNodes.toString());
  console.log("  Peace Threshold:", peaceThreshold.toString(), "BPS");
  
  console.log("\n✓ Deployment complete!");
  
  return address;
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
