// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/OmegaSync.sol";

/**
 * Foundry deployment script for OmegaSync
 * Generated by deploy_omega_sync.js
 * 
 * Usage:
 *   forge script scripts/DeployOmegaSync.s.sol --rpc-url <RPC_URL> --broadcast
 */
contract DeployOmegaSync is Script {
    function run() external {
        // Lex Amoris signature hash
        bytes32 psiSeedHash = 0x87312bcfc82f77e819e9e8861f5076387426188830a9db74b6dd87f6a9d491a2;
        
        console.log("Deploying OmegaSync...");
        console.log("Lex Amoris Signature:");
        console.logBytes32(psiSeedHash);
        
        vm.startBroadcast();
        
        OmegaSync omegaSync = new OmegaSync(psiSeedHash);
        
        vm.stopBroadcast();
        
        console.log("OmegaSync deployed to:");
        console.log(address(omegaSync));
        
        // Verify parameters
        console.log("\nContract Parameters:");
        console.log("  Schumann Frequency (mHz):", omegaSync.SCHUMANN_FREQUENCY_MHZ());
        console.log("  Total Nodes:", omegaSync.TOTAL_NETWORK_NODES());
        console.log("  Peace Threshold (BPS):", omegaSync.PEACE_THRESHOLD_BPS());
    }
}
